# Generated by Django 5.2.3 on 2026-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospitalward',
            table='hospitals_hospitalward',
        ),
        migrations.AlterModelTable(
            name='wardbed',
            table='hospitals_wardbed',
        ),
    ]
