# Generated by Django 5.2.3 on 2025-08-20 19:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role_alter_user_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default=core.models.default_notification_settings),
        ),
    ]
