# Generated by Django 5.2.3 on 2025-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospitaladmin', 'HospitalAdmin'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], default='patient', max_length=20),
        ),
    ]
