# Generated by Django 5.2.3 on 2025-09-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hin',
        ),
    ]
