# Generated by Django 5.2.3 on 2025-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_hin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], default='patient', max_length=20),
        ),
    ]
