# Generated by Django 5.2.3 on 2025-09-01 11:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_house_no_alter_otp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], default='patient', max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(default=core.models.default_expiry)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
