# Generated by Django 5.2.3 on 2025-09-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
