# Generated by Django 5.2.3 on 2025-10-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_paystack_cus_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paystack_cus_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
    ]
