# Generated by Django 5.2.3 on 2025-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], default='patient', max_length=20),
        ),
    ]
