# Generated by Django 5.2.3 on 2025-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
    ]
