# Generated by Django 5.2.3 on 2025-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_cus_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
