# Generated by Django 5.2.3 on 2025-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default={'assessment_diagnosis': {'dashboard': False, 'email': True, 'push': True}, 'info_change': {'dashboard': True, 'email': True, 'push': False}, 'sign_in': {'dashboard': False, 'email': True, 'push': True}}),
        ),
    ]
