# Generated by Django 5.2.3 on 2025-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
