# Generated by Django 5.2.3 on 2025-09-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('medicalrecords', '0001_initial'),
        ('patients', '0002_alter_subaccount_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='hospitals.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='drugrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='patients.patientprofile'),
        ),
    ]
