# Generated by Django 5.2.3 on 2025-09-04 12:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', cloudinary.models.CloudinaryField(max_length=255, verbose_name='medical_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medicalrecords.medicalrecord')),
            ],
        ),
    ]
