# Generated by Django 5.2.3 on 2025-09-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_medicalrecordattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_drug_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_drug_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drugrecord',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='medicalrecords.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_med_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_med_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
