# Generated by Django 5.2.3 on 2025-09-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('medicalrecords', '0002_alter_drugrecord_hospital_alter_drugrecord_patient'),
        ('patients', '0002_alter_subaccount_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_med_records', to='hospitals.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_records', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='referred_docuhealth_hosp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_medical_records', to='hospitals.hospitalprofile'),
        ),
    ]
