# Generated by Django 5.2.3 on 2025-09-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_remove_hospitalprofile_hospital'),
        ('medicalrecords', '0003_alter_medicalrecord_hospital_and_more'),
        ('patients', '0003_patientprofile_deleted_at_patientprofile_hin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='subaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.subaccountprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospitals.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile'),
        ),
    ]
