# Generated by Django 5.2.3 on 2025-09-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_drugrecord_hospital_drugrecord_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecordattachment',
            old_name='attachment',
            new_name='file',
        ),
    ]
