# Generated by Django 5.2.3 on 2025-09-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_doctorprofile_deleted_at_doctorprofile_doc_id_and_more'),
        ('medicalrecords', '0004_medicalrecord_subaccount_and_more'),
        ('patients', '0005_subaccountprofile_hin_alter_subaccountprofile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='hospitals.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='subaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='patients.subaccountprofile'),
        ),
    ]
