# Generated by Django 5.2.3 on 2025-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_rename_attachment_medicalrecordattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
