# Generated by Django 5.2.3 on 2025-09-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_doctorprofile_firstname_doctorprofile_lastname'),
        ('medicalrecords', '0005_alter_medicalrecord_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='hospitals.doctorprofile'),
        ),
    ]
