# Generated by Django 5.2.3 on 2025-09-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_alter_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordattachment',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medicalrecords.medicalrecord'),
        ),
    ]
