# Generated by Django 5.2.3 on 2025-09-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0006_medicalrecord_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
    ]
