# Generated by Django 5.2.3 on 2025-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0007_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
