# Generated by Django 5.2.3 on 2025-10-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0008_medicalrecordattachment_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
