# Generated by Django 5.2.3 on 2025-11-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0025_alter_vitalsigns_heart_rate_alter_vitalsigns_height_and_more'),
        ('medicalrecords', '0010_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='vital_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.vitalsigns'),
        ),
    ]
