# Generated by Django 5.2.3 on 2025-11-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0011_alter_medicalrecord_vital_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrecord',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='ongoing', max_length=20),
        ),
    ]
