# Generated by Django 5.2.3 on 2026-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospitalinquiry',
            table='hospitals_hospitalinquiry',
        ),
        migrations.AlterModelTable(
            name='hospitalprofile',
            table='hospitals_hospitalprofile',
        ),
        migrations.AlterModelTable(
            name='hospitalverificationrequest',
            table='hospitals_hospitalverificationrequest',
        ),
        migrations.AlterModelTable(
            name='paystackcustomer',
            table='subscriptions_paystackcustomer',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions_subscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscriptions_subscriptionplan',
        ),
        migrations.AlterModelTable(
            name='verificationtoken',
            table='hospitals_verificationtoken',
        ),
    ]
