# Generated by Django 5.2.3 on 2026-01-13 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_paystackcustomer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyonboardingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyonboardingrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyonboardingrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
