# Generated by Django 5.2.3 on 2026-01-15 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_pharmacyprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyonboardingrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='request',
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='documents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='license_no',
            field=models.CharField(default='111111111', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='phone',
            field=models.CharField(default='111111111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.pharmacypartner'),
        ),
        migrations.DeleteModel(
            name='PharmacyClient',
        ),
        migrations.DeleteModel(
            name='PharmacyOnboardingRequest',
        ),
    ]
