# Generated by Django 5.2.3 on 2026-01-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_pharmacyonboardingrequest_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacypartner',
            name='email',
        ),
    ]
