# Generated by Django 5.2.3 on 2026-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_pharmacypartner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually')], max_length=20),
        ),
    ]
