# Generated by Django 5.2.3 on 2026-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_subscriptionplan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('test', 'Test')], default='patient', max_length=20),
        ),
    ]
