# Generated by Django 5.2.3 on 2026-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_subscriptionplan_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='theme_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
