# Generated by Django 5.2.3 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_hospitalprofile_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='bg_image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
