# Generated by Django 5.2.3 on 2026-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_hospitalprofile_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='profile_image',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='bg_image',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
