# Generated by Django 5.2.3 on 2026-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
