# Generated by Django 5.2.3 on 2026-03-28 04:32

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_subscription_paystack_subscription_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='notification_settings',
            field=models.JSONField(default=organizations.models.default_notification_settings),
        ),
    ]
