# Generated by Django 5.2.3 on 2026-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospitalpatientactivity',
            new_name='hospitals_h_hospita_ba86b4_idx',
            old_name='hospital_op_hospita_1f1def_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointments_appointment',
        ),
        migrations.AlterModelTable(
            name='hospitalpatientactivity',
            table='hospitals_hospitalpatientactivity',
        ),
    ]
