# Generated by Django 5.2.3 on 2026-01-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ni_user_id_eb8d03_idx_patients_ni_user_id_395752_idx_and_more'),
        ('hospital_ops', '0002_rename_hospital_op_hospita_1f1def_idx_hospitals_h_hospita_ba86b4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandOverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handover_appointments', models.BooleanField(default=False)),
                ('handover_patients', models.BooleanField(default=False)),
                ('items_transferred', models.JSONField()),
                ('from_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_given', to='accounts.hospitalstaffprofile')),
                ('to_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
