# Generated by Django 5.2.3 on 2026-01-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_ops', '0003_handoverlog'),
        ('records', '0006_alter_drugrecord_upload_source_soapnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='soap_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='records.soapnote'),
        ),
    ]
