# Generated by Django 5.2.3 on 2026-01-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_ops', '0004_appointment_soap_note'),
        ('records', '0008_alter_drugrecord_upload_source_dischargeform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discharge_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='records.dischargeform'),
        ),
    ]
