# Generated by Django 5.2.3 on 2026-02-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_ops', '0005_appointment_discharge_form'),
        ('records', '0010_remove_soapnote_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='soap_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='records.soapnote'),
        ),
    ]
