# Generated by Django 5.2.3 on 2026-01-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facility', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='facility.hospitalward'),
        ),
        migrations.AddField(
            model_name='ninverificationattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nin_verification_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subaccountprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='accounts.patientprofile'),
        ),
        migrations.AddField(
            model_name='subaccountprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subaccount_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_img', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ninverificationattempt',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ni_user_id_eb8d03_idx'),
        ),
    ]
