# Generated by Django 5.2.3 on 2026-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ninverificationattempt',
            new_name='patients_ni_user_id_395752_idx',
            old_name='accounts_ni_user_id_eb8d03_idx',
        ),
        migrations.AlterModelTable(
            name='hospitalstaffprofile',
            table='hospitals_hospitalstaffprofile',
        ),
        migrations.AlterModelTable(
            name='ninverificationattempt',
            table='patients_ninverificationattempt',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='core_otp',
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='patients_patientprofile',
        ),
        migrations.AlterModelTable(
            name='subaccountprofile',
            table='patients_subaccountprofile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
        migrations.AlterModelTable(
            name='userprofileimage',
            table='core_userprofileimage',
        ),
    ]
