# Generated by Django 5.2.3 on 2026-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ni_user_id_eb8d03_idx_patients_ni_user_id_395752_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('admin', 'Admin'), ('pharmacy', 'Pharmacy'), ('pharmacy_partner', 'Pharmacy Partner')], max_length=20),
        ),
    ]
