# Generated by Django 5.2.3 on 2026-01-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('dhadmin', 'DHAdmin'), ('pharmacy', 'Pharmacy'), ('pharmacy_partner', 'Pharmacy Partner')], max_length=20),
        ),
    ]
