# Generated by Django 5.2.3 on 2026-02-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalstaffprofile',
            old_name='phone_no',
            new_name='phone_num',
        ),
    ]
