# Generated by Django 5.2.3 on 2026-03-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_phone_no_hospitalstaffprofile_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('subaccount', 'Subaccount'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('dhadmin', 'DHAdmin'), ('pharmacy', 'Pharmacy'), ('pharmacy_partner', 'Pharmacy Partner')], db_index=True, max_length=20),
        ),
    ]
