# Generated by Django 5.2.3 on 2026-03-10 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='hin',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subaccountprofile',
            name='hin',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_emergencey_number', models.CharField()),
                ('second_emergencey_number', models.CharField(blank=True)),
                ('emergence_address', models.CharField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'patients_idcard',
            },
        ),
    ]
