# Generated by Django 5.2.3 on 2026-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otp_created_at_otp_deleted_at_otp_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
