# Generated by Django 5.2.3 on 2026-03-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_is_verified'),
        ('organizations', '0016_alter_hospitalprofile_notification_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_counters', to='organizations.hospitalprofile')),
            ],
            options={
                'unique_together': {('hospital', 'role')},
            },
        ),
    ]
