# Generated by Django 5.2.3 on 2026-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcounter',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
