# Generated by Django 5.2.3 on 2026-03-28 04:49

import re
from django.db import migrations
from django.db.models import Max

def seed_sequences(apps, schema_editor):
    HospitalProfile = apps.get_model('organizations', 'HospitalProfile')
    HospitalStaffProfile = apps.get_model('accounts', 'HospitalStaffProfile')
    StaffCounter = apps.get_model('accounts', 'StaffCounter')

    roles = ["doctor", "nurse", "receptionist"]

    for hospital in HospitalProfile.objects.all():
        for role in roles:
            # Find max for THIS hospital and THIS role
            latest = HospitalStaffProfile.objects.filter(
                hospital=hospital, 
                role=role
            ).aggregate(Max('staff_id'))['staff_id__max']

            current_max = 0
            if latest:
                match = re.search(r'(\d+)$', latest)
                current_max = int(match.group(1)) if match else 0

            StaffCounter.objects.update_or_create(
                hospital=hospital,
                role=role,
                defaults={'current_value': current_max}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_staffcounter_role'),
        ('organizations', '0016_alter_hospitalprofile_notification_settings'),
    ]

    operations = [
        migrations.RunPython(seed_sequences),
    ]