# Generated by Django 5.2.3 on 2025-09-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_deleted_at_appointment_is_deleted'),
        ('medicalrecords', '0007_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='medicalrecords.medicalrecord'),
        ),
    ]
