# Generated by Django 5.2.3 on 2025-09-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_medical_record'),
        ('medicalrecords', '0007_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='medicalrecords.medicalrecord'),
        ),
    ]
