# Generated by Django 5.2.3 on 2025-11-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_medical_record'),
        ('hospitals', '0012_remove_doctorprofile_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospitals.hospitalstaffprofile'),
        ),
    ]
