# Generated by Django 5.2.3 on 2025-11-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='staff',
        ),
    ]
