# Generated by Django 5.2.3 on 2025-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_rename_doctor_appointment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
