# Generated by Django 5.2.3 on 2025-10-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_paystack_plan_id_subscriptionplan_paystack_plan_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='will_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past_due', 'Past_Due')], default='inactive', max_length=20),
        ),
    ]
