# Generated by Django 5.2.3 on 2026-01-08 10:29

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facility', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('discharged', 'Discharged')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='facility.wardbed')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='accounts.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='accounts.hospitalstaffprofile')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='facility.hospitalward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history', models.JSONField(default=list)),
                ('physical_exam', models.JSONField(default=list)),
                ('diagnosis', models.JSONField(default=list)),
                ('treatment_plan', models.JSONField(default=list)),
                ('care_instructions', models.JSONField(default=list)),
                ('referred_hosp', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.hospitalstaffprofile')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.patientprofile')),
                ('referred_docuhealth_hosp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_medical_records', to='organizations.hospitalprofile')),
                ('subaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.subaccountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DrugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('frequency', models.JSONField(default=dict)),
                ('duration', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='accounts.patientprofile')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='medical_records/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('temp', models.FloatField(blank=True, max_length=100, null=True)),
                ('resp_rate', models.FloatField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, max_length=100, null=True)),
                ('heart_rate', models.FloatField(blank=True, max_length=100, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='accounts.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.vitalsigns'),
        ),
        migrations.CreateModel(
            name='VitalSignsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed')], default='requested', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='accounts.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
