# Generated by Django 5.2.3 on 2026-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='hospitals_admission',
        ),
        migrations.AlterModelTable(
            name='drugrecord',
            table='medicalrecords_drugrecord',
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medicalrecords_medicalrecord',
        ),
        migrations.AlterModelTable(
            name='medicalrecordattachment',
            table='medicalrecords_medicalrecordattachment',
        ),
        migrations.AlterModelTable(
            name='vitalsigns',
            table='hospitals_vitalsigns',
        ),
        migrations.AlterModelTable(
            name='vitalsignsrequest',
            table='hospitals_vitalsignsrequest',
        ),
    ]
