# Generated by Django 5.2.3 on 2026-01-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ni_user_id_eb8d03_idx_patients_ni_user_id_395752_idx_and_more'),
        ('organizations', '0002_alter_hospitalinquiry_table_and_more'),
        ('records', '0002_alter_admission_table_alter_drugrecord_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('care', models.TextField()),
                ('response', models.TextField()),
                ('abnormalities', models.TextField(blank=True, null=True)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='accounts.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
