# Generated by Django 5.2.3 on 2026-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_casenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='abnormalities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='care',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='follow_up',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='observation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='response',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
