# Generated by Django 5.2.3 on 2026-01-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_pharmacyonboardingrequest_created_at_and_more'),
        ('records', '0004_alter_casenote_abnormalities_alter_casenote_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrecord',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_records', to='organizations.pharmacyprofile'),
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='upload_source',
            field=models.CharField(choices=[('medicalrecord', 'Medical Record'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('pharmacy_api', 'Pharmacy API')], default='medicalrecord', max_length=20),
        ),
    ]
