# Generated by Django 5.2.3 on 2026-01-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('hospital_ops', '0003_handoverlog'),
        ('organizations', '0008_remove_pharmacypartner_email'),
        ('records', '0005_drugrecord_allergies_drugrecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrecord',
            name='upload_source',
            field=models.CharField(choices=[('medicalrecord', 'Medical Record'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('pharmacy_api', 'Pharmacy API'), ('soap_note', 'SOAP Note')], default='medicalrecord', max_length=20),
        ),
        migrations.CreateModel(
            name='SoapNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('past_med_history', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('social_history', models.TextField(blank=True, null=True)),
                ('drug_history_allergies', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('general_exam', models.TextField(blank=True, null=True)),
                ('systemic_exam', models.TextField(blank=True, null=True)),
                ('bedside_tests', models.TextField(blank=True, null=True)),
                ('investigations', models.JSONField(blank=True, default=list, null=True)),
                ('investigations_docs', models.JSONField(blank=True, default=list, null=True)),
                ('primary_diagnosis', models.TextField()),
                ('differential_diagnosis', models.TextField(blank=True, null=True)),
                ('problem_list', models.JSONField(blank=True, default=list, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('care_instructions', models.JSONField(default=list)),
                ('referred_hosp', models.TextField(blank=True, null=True)),
                ('patient_education', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soap_notes', to='hospital_ops.appointment')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soap_notes', to='organizations.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_notes', to='accounts.patientprofile')),
                ('referred_docuhealth_hosp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_soap_notes', to='organizations.hospitalprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soap_notes', to='accounts.hospitalstaffprofile')),
                ('vital_signs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.vitalsigns')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='soap_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_records', to='records.soapnote'),
        ),
    ]
