# Generated by Django 5.2.3 on 2026-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_drugrecord_upload_source_soapnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapnote',
            old_name='history',
            new_name='history_of_complain',
        ),
        migrations.AddField(
            model_name='soapnote',
            name='other_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='bedside_tests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='general_exam',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='systemic_exam',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='treatment_plan',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
