# Generated by Django 5.2.3 on 2026-01-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('hospital_ops', '0004_appointment_soap_note'),
        ('records', '0007_rename_history_soapnote_history_of_complain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrecord',
            name='upload_source',
            field=models.CharField(choices=[('medicalrecord', 'Medical Record'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('pharmacy_api', 'Pharmacy API'), ('soap_note', 'SOAP Note'), ('discharge_form', 'Discharge Form')], default='medicalrecord', max_length=20),
        ),
        migrations.CreateModel(
            name='DischargeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation_docs', models.JSONField(blank=True, default=list, null=True)),
                ('follow_up_appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharge_forms', to='hospital_ops.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_form', to='accounts.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_form', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drugrecord',
            name='discharge_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_records', to='records.dischargeform'),
        ),
    ]
