# Generated by Django 5.2.3 on 2026-02-01 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_drugrecord_upload_source_dischargeform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapnote',
            old_name='problem_list',
            new_name='problems_list',
        ),
        migrations.CreateModel(
            name='SoapNoteAdditionalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('soap_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_notes', to='records.soapnote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
