# Generated by Django 5.2.3 on 2026-02-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_rename_problem_list_soapnote_problems_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapnote',
            name='appointment',
        ),
    ]
