# Generated by Django 5.2.3 on 2026-02-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('organizations', '0008_remove_pharmacypartner_email'),
        ('records', '0010_remove_soapnote_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargeform',
            name='patient',
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_form', to='records.admission'),
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_forms', to='organizations.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='dischargeform',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_forms', to='accounts.hospitalstaffprofile'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='drug_history_allergies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
