# Generated by Django 5.2.3 on 2026-02-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_dischargeform_patient_dischargeform_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargeform',
            name='admission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_form', to='records.admission'),
            preserve_default=False,
        ),
    ]
