# Generated by Django 5.2.3 on 2026-02-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_dischargeform_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargeform',
            name='care_instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='chief_complaint',
            field=models.TextField(default='Watermelon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='condition_on_discharge',
            field=models.TextField(default='Watermelon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='diagnosis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dischargeform',
            name='treatment_plan',
            field=models.JSONField(default=list),
        ),
    ]
