# Generated by Django 5.2.3 on 2026-02-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_dischargeform_care_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargeform',
            name='follow_up_appointment',
        ),
    ]
