# Generated by Django 5.2.3 on 2026-02-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_dischargeform_follow_up_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapnote',
            old_name='investigations_docs',
            new_name='investigation_docs',
        ),
    ]
