# Generated by Django 5.2.3 on 2025-09-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='hospital',
        ),
    ]
