# Generated by Django 5.2.3 on 2025-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospitalprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hin',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
