# Generated by Django 5.2.3 on 2025-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospitalprofile_deleted_at_hospitalprofile_hin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_id',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
