# Generated by Django 5.2.3 on 2025-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_doctorprofile_deleted_at_doctorprofile_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
