# Generated by Django 5.2.3 on 2025-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_doctorprofile_firstname_doctorprofile_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Contacted', 'contacted'), ('Closed', 'closed')], default='Pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
