# Generated by Django 5.2.3 on 2025-10-29 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_alter_hospitalinquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalverificationrequest',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='hospitals.hospitalinquiry'),
        ),
    ]
