# Generated by Django 5.2.3 on 2025-10-31 15:01

import hospitals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_doctorprofile_created_at_hospitalprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='notification_settings',
            field=models.JSONField(default=hospitals.models.default_notification_settings),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='paystack_cus_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
