# Generated by Django 5.2.3 on 2025-11-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_doctor'),
        ('hospitals', '0012_remove_doctorprofile_hospital_and_more'),
        ('medicalrecords', '0010_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
