# Generated by Django 5.2.3 on 2025-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_delete_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='male'),
            preserve_default=False,
        ),
    ]
