# Generated by Django 5.2.3 on 2025-11-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0015_patientinteraction'),
        ('patients', '0010_patientprofile_city_patientprofile_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInteraction',
            new_name='HospitalPatientActivity',
        ),
        migrations.RenameIndex(
            model_name='hospitalpatientactivity',
            new_name='hospitals_h_hospita_ba86b4_idx',
            old_name='hospitals_p_hospita_6a0832_idx',
        ),
    ]
