# Generated by Django 5.2.3 on 2025-11-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_rename_patientinteraction_hospitalpatientactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospitals.hospitalprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
