# Generated by Django 5.2.3 on 2025-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0017_hospitalward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalward',
            old_name='beds',
            new_name='total_beds',
        ),
        migrations.AddField(
            model_name='hospitalward',
            name='available_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
