# Generated by Django 5.2.3 on 2025-11-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0018_rename_beds_hospitalward_total_beds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalward',
            name='available_beds',
        ),
        migrations.CreateModel(
            name='WardBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed_number', models.IntegerField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.hospitalward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
