# Generated by Django 5.2.3 on 2025-11-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0019_remove_hospitalward_available_beds_wardbed'),
        ('patients', '0010_patientprofile_city_patientprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardbed',
            name='bed_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('discharged', 'Discharged')], default='pending', max_length=20)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospitals.wardbed')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospitals.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospitals.hospitalstaffprofile')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospitals.hospitalward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
