# Generated by Django 5.2.3 on 2025-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0020_alter_wardbed_bed_number_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardbed',
            name='is_available',
        ),
        migrations.AddField(
            model_name='wardbed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('requested', 'Requested')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('discharged', 'Discharged')], default='pending', max_length=20),
        ),
    ]
