# Generated by Django 5.2.3 on 2025-11-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0021_remove_wardbed_is_available_wardbed_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hospitals.hospitalward'),
        ),
    ]
