# Generated by Django 5.2.3 on 2025-11-19 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0022_hospitalstaffprofile_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
