# Generated by Django 5.2.3 on 2025-11-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0023_admission_request_date_and_more'),
        ('patients', '0010_patientprofile_city_patientprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('temp', models.CharField(blank=True, max_length=100, null=True)),
                ('resp_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='hospitals.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='patients.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='hospitals.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VitalSignsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed')], default='requested', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='hospitals.hospitalprofile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='patients.patientprofile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_requests', to='hospitals.hospitalstaffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
