# Generated by Django 5.2.3 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0024_vitalsigns_vitalsignsrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='heart_rate',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='resp_rate',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temp',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
