# Generated by Django 5.2.3 on 2025-11-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0025_alter_vitalsigns_heart_rate_alter_vitalsigns_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='paystack_cus_code',
        ),
    ]
