# Generated by Django 5.2.3 on 2025-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subaccount',
            name='hin',
        ),
        migrations.RemoveField(
            model_name='subaccount',
            name='updated_at',
        ),
    ]
