# Generated by Django 5.2.3 on 2025-09-09 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_subaccount_created_at_remove_subaccount_hin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
