# Generated by Django 5.2.3 on 2025-09-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccountprofile',
            name='hin',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subaccountprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='patients.patientprofile'),
        ),
    ]
