# Generated by Django 5.2.3 on 2025-10-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_subaccountprofile_hin_alter_subaccountprofile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccountprofile',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
