# Generated by Django 5.2.3 on 2025-09-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_subaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
