# Generated by Django 5.2.3 on 2025-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_subaccountprofile_id_card_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaccountprofile',
            name='id_card_generated',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
