# Generated by Django 5.2.3 on 2025-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_subaccountprofile_id_card_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccountprofile',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
