# Generated by Django 5.2.3 on 2025-11-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientprofile_city_patientprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='paystack_cus_code',
        ),
    ]
