# Generated by Django 5.2.3 on 2025-12-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_patientprofile_nin_patientprofile_nin_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='nin',
            new_name='nin_hash',
        ),
    ]
