# Generated by Django 5.2.3 on 2025-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_rename_nin_patientprofile_nin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='nin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
